-- Migration to support AI/Human badges in messaging
ALTER TABLE messages ADD COLUMN IF NOT EXISTS is_ai BOOLEAN DEFAULT false;

-- Add a comment for clarity
COMMENT ON COLUMN messages.is_ai IS 'Indicates if the message was generated by the AI simulation in the Playground.';
