/*
  ========================================================================
  🛒 SÓC DE POBLE - PROTOCOLO OMEGA-23 (V8): CURACIÓN DEL ID
  ========================================================================
  🎯 Objetivo: 
  Se detectó que Supabase tenía la columna 'id' configurada como BIGINT 
  clásico, pero había perdido su propiedad autoincremental (IDENTITY).
  
  Aquí primero forzamos estáticamente que PostgreSQL recupere el control 
  del autoincrement mediante un ALTER TABLE preventivo y después insertamos 
  dejando que postgres actúe solo. CERO NULLS garantizados y Frontend salvado.
*/

DO $$ 
BEGIN
  -- 0. SANEAR COLUMNA ID (Restaurar Identity Permanente)
  -- Si en el pasado perdió su propiedad autoincremental, aquí la forzamos
  BEGIN
    ALTER TABLE public.market_items ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
  EXCEPTION WHEN OTHERS THEN
    NULL; -- Si ya tiene identity o da conflicto, lo ignoramos y continuamos
  END;
END $$;

DO $$ 
DECLARE
  v_admin_id uuid;
  v_admin_name text;
  v_admin_avatar text;

  v_iaia_id uuid;
  v_iaia_name text;
  v_iaia_avatar text;

  v_entity_coop uuid;
  v_entity_forn uuid;
  v_entity_ajuntament uuid;

  v_town_id int;
  v_town_uuid uuid;
BEGIN

  -- 1. Atrapar el UUID del Admin
  SELECT id INTO v_admin_id FROM auth.users ORDER BY created_at ASC LIMIT 1;
  SELECT full_name, avatar_url INTO v_admin_name, v_admin_avatar 
  FROM public.profiles 
  WHERE id = v_admin_id LIMIT 1;

  IF v_admin_name IS NULL THEN v_admin_name := 'Sóc de Poble (Oficial)'; END IF;
  IF v_admin_avatar IS NULL THEN v_admin_avatar := '/assets/master/logo_socdepoble_green_square.png'; END IF;

  -- 2. Atrapar la IAIA MarIA
  SELECT name, avatar_url INTO v_iaia_name, v_iaia_avatar 
  FROM public.system_agents WHERE name = 'IAIA MarIA' LIMIT 1;
  
  v_iaia_id := v_admin_id; 

  IF v_iaia_name IS NULL THEN v_iaia_name := 'IAIA MarIA'; END IF;
  IF v_iaia_avatar IS NULL THEN v_iaia_avatar := '/assets/avatars/comic/iaia_comic_matriarch.png'; END IF;

  -- 3. Atrapar Entidades
  SELECT id INTO v_entity_coop FROM public.entities WHERE name ILIKE '%Cooperativa%' LIMIT 1;
  SELECT id INTO v_entity_forn FROM public.entities WHERE name ILIKE '%Forn%' LIMIT 1;
  SELECT id INTO v_entity_ajuntament FROM public.entities WHERE name ILIKE '%Ajuntament%' OR name ILIKE '%Turisme%' LIMIT 1;
  SELECT id INTO v_entity_sdp FROM public.entities WHERE name ILIKE '%Sóc de Poble%' LIMIT 1;

  IF v_entity_coop IS NULL THEN v_entity_coop := v_admin_id; END IF;
  IF v_entity_forn IS NULL THEN v_entity_forn := v_entity_coop; END IF;
  IF v_entity_ajuntament IS NULL THEN v_entity_ajuntament := v_entity_coop; END IF;
  IF v_entity_sdp IS NULL THEN v_entity_sdp := v_entity_ajuntament; END IF;

  -- 4. Atrapar un Pueblo Local
  SELECT id, uuid INTO v_town_id, v_town_uuid FROM public.towns LIMIT 1;

  -- 5. PURGA MASIVA ANTES DE LA RE-INYECCIÓN
  DELETE FROM public.market_items;

  -- 6. INYECCIÓN CATEDRAL (DEJANDO QUE SUPABASE AUTOGENERE EL ID NUMÉRICO)
  INSERT INTO public.market_items (
    title, price, image_url, category_slug, description, 
    author_user_id, author_entity_id, avatar_url,  
    town_uuid, is_playground
  )
  VALUES 
  (
    'Formatge Madurat d''Ovella (Artisanal)', 15, '/assets/market/formatge_premium.png', 'alimentacio', 
    '<h1>Formatge Madurat d''Ovella</h1><h2>Autèntic i Artesanal</h2><p>Aquest formatge madurat a la cova és una delícia per als sentits. Hem utilitzat herbes aromàtiques de la serra per donar-li un toc especial. És ideal per a l''esmorzar, acompanyat d''un bon pa de llenya i un vi negre de la terra. La maduració acurada garanteix una textura ferma i un sabor intens que perdura en la memòria.</p>',
    v_admin_id, v_entity_coop, v_admin_avatar, 
    v_town_uuid, FALSE
  ),
  (
    'Melmelada de Tomaca Ecològica', 4.50, '/assets/market/tomaca_pot.png', 'alimentacio', 
    '<h1>Melmelada Casolana</h1><h2>Feta al caliu del foc</h2><p>He passat matins sencers preparant aquesta melmelada amb les tomaques més roges i madures de la nostra horta. Cap classe de pesticida ni químic ha tocat la nostra terra. Aquest pot porta el sabor de l''estiu i és la guinda perfecta per a unes bones torrades al costat del rusc blanc. Tasteu-la, vos portarà records de l''antigor.</p>',
    v_iaia_id, v_entity_coop, v_iaia_avatar, 
    v_town_uuid, FALSE
  ),
  (
    'Pantalons de Muntanya Resistents', 45, '/assets/market/pantalons_roba.png', 'roba', 
    '<h1>Equipament Tècnic</h1><h2>Resistència assegurada</h2><p>Dissenyats per resistir els esbarzers i el clima canviant de la muntanya. Aquests pantalons tècnics destaquen per la seua capacitat de secatge ultraràpid i les costures reforçades als punts crítics. Ideals per fer rutes exigents de senderisme. No permetràs que una ventada ature el teu cap de setmana de desconnexió verda.</p>',
    v_admin_id, v_entity_ajuntament, v_admin_avatar, 
    v_town_uuid, FALSE
  ),
  (
    'Oli Verge Extra - Garrafa 5L', 38, '/assets/market/oli_premium.png', 'alimentacio', 
    '<h1>Oli de Blanqueta</h1><h2>Del camp a la taula</h2><p>Posem a la teua disposició una garrafa de cinc litres d''or líquid pur. Oli de la primera premsada en fred 100% de la varietat Blanqueta, tan típica a la nostra comarca. Manté tota la seua densitat, picantor i aroma a fruita tendra. Directament de l''almàssera al teu plat de la llar, perfecte per a amanides i conserves.</p>',
    v_admin_id, v_entity_coop, v_admin_avatar,
    v_town_uuid, FALSE
  ),
  (
    'Pa Tradicional de Llenya', 2.50, '/assets/market/pa_llenya.png', 'alimentacio', 
    '<h1>El pa d''abans</h1><h2>Cuit a l''estil morú</h2><p>Repetim la recepta diària tal com ens la van ensenyar els nostres majors. El pa de tota la vida, pastat a mà amb temps de fermentació reposada, i cuit al forn morú de llenya de matoll fort. Crosta fosca i super cruixent que amaga una molla blanca perfecta per omplir amb oli d''oliva i una anxoveta bona.</p>',
    v_admin_id, v_entity_forn, v_admin_avatar,
    v_town_uuid, FALSE
  ),
  (
    'Cabàs Tradicional d''Espart', 28, '/assets/market/cabas_espart.png', 'artesania', 
    '<h1>Trenat a Mà</h1><h2>Espart del roquissar</h2><p>Elaborat íntegrament per mi, unint i cordant l''espart que abans col·líem i secàvem. És fort i elàstic, seguint fil per randa la tècnica centenària apresa de menuda. Serà el teu millor complement ecològic. Perfecte per a anar a comprar fruita fresca al mercat del dilluns sense gastar ni un cèntim en bosses de plàstic inútils.</p>',
    v_iaia_id, v_entity_ajuntament, v_iaia_avatar,
    v_town_uuid, FALSE
  ),
  (
    'Vi Negre Criança de la Marina', 12, '/assets/market/vi_negre.png', 'alimentacio', 
    '<h1>Negre amb Solera</h1><h2>12 mesos en bóta</h2><p>Aquest vi negre madura sota una estricta vigilància amb presència de roure durant tot un any sencer. Té evidents notes de bosc profund i essència a fruita madura pruna tendra. Neix a la nostra comarca gràcies a l''assolellat vent de l''est. Combina especialment amb arrossos de muntanya, carns guisades i nits fresquetes a la vora del foc.</p>',
    v_admin_id, v_entity_coop, v_admin_avatar,
    v_town_uuid, FALSE
  ),
  (
    'Botes d''Alpinisme PobleGrip', 89, '/assets/market/botes_trekking.png', 'roba', 
    '<h1>Caminades Segures</h1><h2>Grip superior en terreny sec</h2><p>Especialitzades al màxim rendiment amb sola antilliscant super adherents i membrana lleugerament impermeable que respira bé. Recomanades per als llargs dies de neu esporàdica o el xoc constant contra les formacions rocoses dentades dels nostres cims. Assegura les teues cames i no patisques per relliscar quan plou poc però l''herba es queda mullada.</p>',
    v_admin_id, v_entity_ajuntament, v_admin_avatar,
    v_town_uuid, FALSE
  ),
  (
    'Sabó Ecològic d''Oli d''Oliva', 6, '/assets/market/sabo_artesa.png', 'artesania', 
    '<h1>Fet a casa</h1><h2>Neteja de la puresa d''abans</h2><p>L''autèntic sabó natural de les nostres àvies. Creat barrejant acuradament la sosa amb l''oli sobrant molt net de l''almàssera, i finalment aromatitzat amb espígol local secat a l''ombra fresca. Escuma perfecta, ideal per tractar peces tacades i completament inofensiu per a aquells que pateixen de pell seca. El verdader miracle econòmic i pràctic reciclant recursos bons.</p>',
    v_iaia_id, v_entity_coop, v_iaia_avatar,
    v_town_uuid, FALSE
  ),
  (
    'Samarreta Sóc de Poble', 12, '/assets/market/samarreta_festes.png', 'roba', 
    '<h1>Equipament Oficial</h1><h2>L''Autèntica, L''Original</h2><p>La samarreta oficial i canònica de la plataforma Sóc de Poble. Disseny exclusiu, producció ètica i de màxima qualitat per no suar com un titot. Amb el logotip icònic al pit per a que tot el món sàpiga d''on vens. Disposa de talles molt variades, garantint l''ajust ideal des de XS fins a complets XXL. Fes comarca!</p>',
    v_admin_id, v_entity_sdp, '/assets/master/logo_socdepoble_green_square.png',
    v_town_uuid, FALSE
  ),
  (
    'Ruta Guiada: El Barranc Ocult', 0, '/assets/market/ruta_guiada.png', 'eines', 
    '<h1>Natura Intacta</h1><h2>Descobreix i protegeix l''entorn nostre</h2><p>Excursió col·lectiva assequible a qualsevol membre on passejarem per a netejar part baixa dels marges fluvials, compartint anècdotes altes i coneixent els petits camins oblidats dels pastors. Cal dur roba de caminar eficient, aigua a munts, l''esmorzar sòlid de la setmana per als punts de descans curts establerts, i mil ganes fermes de descobrir un terreny meravellós en bona companyia gran.</p>',
    v_admin_id, v_entity_ajuntament, v_admin_avatar,
    v_town_uuid, FALSE
  ),
  (
    'Mel de Romer Pura (1Kg)', 14, '/assets/market/mel_premium.png', 'alimentacio', 
    '<h1>Mel Autèntica Local</h1><h2>Romaní directe al paladar sencer</h2><p>Una joia ensucrada absolutament lliure d''edulcorants fets, conservants foscs o aromes estranyes. Mel daurada, crua i acabada de tallar fa relativament poc i completament sense filtrar. Recollida per atetes abelles naturals autòctones de les caixes de fusta local. Textura divina super bona per clavar amb nous salades a un iogurt fresn clàssic casolà de cabra amb sucre.</p>',
    v_admin_id, v_entity_coop, v_admin_avatar, 
    v_town_uuid, FALSE
  );

  RAISE NOTICE '✅ PROTOCOLO OMEGA-23 (V8 IDENTITY FIX): Insertados. Los IDs numéricos se han sanado y PostgreSQL gestiona el conteo solo.';
END $$;
