// src/constants/lore.js
// Constants de negoci i de lore de Sóc de Poble

export const LORE_PERSONAS = [{
  id: '11111111-1a1a-0000-0000-000000000000',
  full_name: 'IAIA MarIA',
  username: 'iaia_master',
  gender: 'female',
  role: 'official',
  ofici: 'Matriarca Digital',
  primary_town: 'Sóc de Poble (Global)',
  bio: 'Dignitat, terra i xarxa. Soc la teua assistenta (MArIA: Memòria Artificial i Acció) per a tot el que necessites al poble.',
  avatar_url: '/uploads/avatars/iaia_comic_matriarch.png',
  category: 'gent',
  type: 'person',
  onomatopoeia: '🏺',
  time: 'Sempre'
}, {
  id: '11111111-1a1a-0001-0000-000000000001',
  full_name: 'Andreu Soler',
  username: 'andreu-soler',
  gender: 'male',
  role: 'ambassador',
  ofici: 'Capatàs del Mas',
  primary_town: 'La Torre de les Maçanes',
  bio: "L'Andreu és el rellotge del camp.",
  avatar_url: '/uploads/avatars/andreu-soler-comic.png',
  onomatopoeia: '¡PLAS!',
  category: 'treball',
  type: 'person',
  time: '3:35 p. m.'
}, {
  id: '11111111-1a1a-0001-0000-000000000002',
  full_name: 'Beatriz Ortega',
  username: 'beatriz-ortega',
  gender: 'female',
  role: 'ambassador',
  ofici: 'Arquitecta de Ferro',
  primary_town: 'Global',
  bio: 'Mestre, la V15 està bategant forta!',
  avatar_url: '/uploads/avatars/beatriz-ortega-comic.png',
  onomatopoeia: '¡CLINC!',
  category: 'treball',
  type: 'person',
  time: '12:19 p. m.'
}, {
  id: '11111111-1a1a-0001-0000-000000000003',
  full_name: 'Carla Soriano',
  username: 'carla-soriano',
  gender: 'female',
  role: 'ambassador',
  ofici: 'Harmonitzadora de Batecs',
  primary_town: 'Ibi',
  bio: 'Bategat equilibrat, mestre Javi.',
  avatar_url: '/uploads/avatars/carla-soriano_comic.png',
  onomatopoeia: '¡OMMM!',
  category: 'gent',
  type: 'person',
  time: '6:13 p. m.'
}, {
  id: '11111111-1111-4111-a111-000000000009',
  full_name: 'Carmen la del Forn',
  username: 'cuinera',
  gender: 'female',
  role: 'ambassador',
  ofici: 'Cuinera del Mas',
  primary_town: 'La Torre de les Maçanes',
  bio: 'La cuina de Pepica és el cor del Mas.',
  avatar_url: '/uploads/avatars/beatriz-ortega-comic.png',
  onomatopoeia: '¡XUP!',
  category: 'treball',
  type: 'person',
  time: '2:16 p. m.'
}, {
  id: '11111111-1111-4111-a111-000000000003',
  full_name: 'Vicent Ferris',
  username: 'vferris',
  gender: 'male',
  role: 'ambassador',
  ofici: 'Agricultor Gran',
  primary_town: 'La Torre de les Maçanes',
  bio: 'Els cicles lunars manen sobre la collita.',
  avatar_url: '/uploads/avatars/vicent-ferris-comic.png',
  onomatopoeia: '¡ZAS!',
  category: 'treball',
  type: 'person',
  time: '5:00 a. m.'
}, {
  id: '11111111-1111-4111-a111-000000000004',
  full_name: 'Samir Mensah',
  username: 'samirm',
  gender: 'male',
  role: 'ambassador',
  ofici: 'Artesà',
  primary_town: 'Ibi',
  bio: 'Integrant tradicions.',
  avatar_url: '/uploads/avatars/avatar_samir_comic.png',
  onomatopoeia: '¡TAC!',
  category: 'gent',
  type: 'person',
  time: '4:15 p. m.'
}, {
  id: '11111111-1111-4111-a111-000000000005',
  full_name: 'Mariamel',
  username: 'mariamel',
  gender: 'female',
  role: 'ambassador',
  ofici: 'Historiadora',
  primary_town: 'Muro',
  bio: 'Conservant el llegat del poble.',
  avatar_url: '/uploads/products/avatar_mariamel_comic.png',
  onomatopoeia: '¡SHH!',
  category: 'gent',
  type: 'person',
  time: '1:00 p. m.'
}, {
  id: '11111111-1111-4111-a111-000000000008',
  full_name: 'Joan Batiste (Avi dels Papers)',
  username: 'joanbat',
  gender: 'male',
  role: 'ambassador',
  ofici: 'Arxiver',
  primary_town: 'Cocentaina',
  bio: 'Tots els documents en regla.',
  avatar_url: '/uploads/avatars/joan-batiste-comic.png',
  onomatopoeia: '¡RASS!',
  category: 'gent',
  type: 'person',
  time: '10:00 a. m.'
}, {
  id: '11111111-0000-0000-0000-000000000004',
  full_name: 'Marc (El Gall)',
  username: 'marcgall',
  gender: 'male',
  role: 'official',
  ofici: 'Alertes Globals',
  primary_town: 'Global',
  bio: 'Alçant al Mas cada dia.',
  avatar_url: '/uploads/avatars/avatar-marc-comic.png',
  onomatopoeia: '¡KIKIRIKI!',
  category: 'gent',
  type: 'person',
  time: '6:00 a. m.'
}, {
  id: '11111111-1111-4111-a111-000000000011',
  full_name: 'Elena Popova',
  username: 'elenap',
  gender: 'female',
  role: 'ambassador',
  ofici: 'Innovadora',
  primary_town: 'Agost',
  bio: "Buscant el futur a l'entorn rural.",
  avatar_url: '/uploads/avatars/elena-popova-comic.png',
  onomatopoeia: '¡PING!',
  category: 'gent',
  type: 'person',
  time: '2:30 p. m.'
}, {
  id: '11111111-1111-4111-a111-000000000012',
  full_name: 'Joanet Serra',
  username: 'joanets',
  gender: 'male',
  role: 'ambassador',
  ofici: 'Sereno',
  primary_town: 'Relleu',
  bio: 'Vigilant les estreles.',
  avatar_url: '/uploads/avatars/joanet-serra-comic.png',
  onomatopoeia: '¡FIUU!',
  category: 'gent',
  type: 'person',
  time: '11:00 p. m.'
}, {
  id: '11111111-1111-4111-a111-000000000013',
  full_name: 'Lucia',
  username: 'lucia',
  gender: 'female',
  role: 'ambassador',
  ofici: 'Llibretera',
  primary_town: 'Banyeres',
  bio: 'La màgia dels contes vells.',
  avatar_url: '/uploads/avatars/avatar_lucia_comic.png',
  onomatopoeia: '¡CLAP!',
  category: 'gent',
  type: 'person',
  time: '5:45 p. m.'
}, {
  id: '11111111-1a1a-0001-0000-000000000007',
  full_name: 'Pepica la de la Vall',
  username: 'pepica_vall',
  gender: 'female',
  role: 'ambassador',
  ofici: 'Herbolària',
  primary_town: 'La Vall',
  bio: 'Remeis naturals.',
  avatar_url: '/uploads/avatars/pepica-vall-comic.png',
  onomatopoeia: '¡TSH!',
  category: 'treball',
  type: 'person',
  time: '8:00 a. m.'
}, {
  id: '11111111-1a1a-0000-0000-000000000005',
  full_name: 'Nano Banana',
  username: 'nanob',
  gender: 'male',
  role: 'official',
  ofici: 'Artista T.I.A.',
  primary_town: 'Global',
  bio: '🎨 Píxels i humor.',
  avatar_url: '/uploads/avatars/nano-banana-comic.png',
  onomatopoeia: '¡POW!',
  category: 'gent',
  type: 'person',
  time: '4:20 p. m.'
}];