import { useState, useEffect } from 'react';
import { logger } from '../utils/logger';

// Path to the credits file generated by the scraper
const CREDITS_PATH = '/assets/pobles/credits.json';

export const useAttribution = (filename) => {
    const [attribution, setAttribution] = useState(null);

    useEffect(() => {
        if (!filename) {
            setAttribution(null);
            return;
        }

        const fetchCredits = async () => {
            try {
                // In a production app, we might want to load this once at the app level
                // but for now, simple fetch is fine as it's a small static JSON.
                const response = await fetch(CREDITS_PATH);
                if (!response.ok) throw new Error('Failed to load credits');

                const data = await response.json();

                // If it's a full URL, get just the filename
                const cleanFilename = filename.split('/').pop();

                if (data[cleanFilename]) {
                    setAttribution(data[cleanFilename]);
                } else {
                    setAttribution(null);
                }
            } catch (err) {
                logger.warn('[useAttribution] Error loading credits:', err);
                setAttribution(null);
            }
        };

        fetchCredits();
    }, [filename]);

    return attribution;
};
