#!/usr/bin/env node
// Migration script: group flat _skills/*.md into domain packages (core/, domain/, tactical/)
// Creates package folders following Agent-Skills style and updates/creates _skills/catalog.yaml
// Usage: node _scripts/migrate-skills.js
// Run from repo root. This script is idempotent for already-migrated files.

const fs = require('fs');
const path = require('path');
const os = require('os');

const SKILLS_ROOT = path.join(process.cwd(), '_skills');
const CATALOG_PATH = path.join(SKILLS_ROOT, 'catalog.yaml');
const DOMAINS = ['core', 'domain', 'tactical']; // adjust as needed

function safeMkdir(p) {
  if (!fs.existsSync(p)) fs.mkdirSync(p, { recursive: true });
}

function readMdFrontmatter(content) {
  // crude frontmatter parse: look for YAML between --- ... ---
  if (!content.startsWith('---')) return null;
  const end = content.indexOf('---', 3);
  if (end === -1) return null;
  const raw = content.slice(3, end).trim();
  const lines = raw.split(/\r?\n/);
  const obj = {};
  for (const line of lines) {
    const m = line.match(/^([^:]+):\s*(.*)$/);
    if (m) obj[m[1].trim()] = m[2].trim().replace(/^["']|["']$/g, '');
  }
  return obj;
}

function slugify(s) {
  return s.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-+|-+$/g, '');
}

function yamlEscape(s) {
  if (s == null) return '';
  return String(s).replace(/\n/g, '\\n').replace(/"/g, '\\"');
}

function loadCatalog() {
  if (!fs.existsSync(CATALOG_PATH)) return { version: 1, generated_at: new Date().toISOString(), load_strategy: 'progressive_disclosure', manifest: [] };
  const txt = fs.readFileSync(CATALOG_PATH, 'utf8');
  // very small YAML parser for our simple structure: find manifest entries by id
  // fallback: return minimal structure and append new entries
  return { version: 1, generated_at: new Date().toISOString(), load_strategy: 'progressive_disclosure', manifest: [] , raw: txt };
}

function writeCatalog(obj) {
  const lines = [];
  lines.push(`# catalog.yaml - generated by migrate-skills.js`);
  lines.push(`version: ${obj.version}`);
  lines.push(`generated_at: ${obj.generated_at}`);
  lines.push(`load_strategy: ${obj.load_strategy}`);
  lines.push(`chunk_size: 8`);
  lines.push(`manifest:`);
  for (const e of obj.manifest) {
    lines.push(`  - id: ${e.id}`);
    lines.push(`    version: "${e.version || '1.0.0'}"`);
    lines.push(`    title: "${e.title.replace(/"/g, '\\"')}"`);
    lines.push(`    summary: "${(e.summary||'').replace(/"/g, '\\"')}"`);
    lines.push(`    entry: "${e.entry}"`);
    lines.push(`    path: "${e.path}"`);
    if (e.size_bytes) lines.push(`    size_bytes: ${e.size_bytes}`);
    if (e.checksum) lines.push(`    checksum: "${e.checksum}"`);
    if (e.tags && e.tags.length) lines.push(`    tags: [${e.tags.map(t => `"${t}"`).join(',')}]`);
    lines.push(`    activation:`);
    lines.push(`      mode: on_demand`);
    if (e.triggers && e.triggers.length) lines.push(`      triggers: [${e.triggers.map(t => `"${t}"`).join(',')}]`);
    lines.push(`    permissions:`);
    lines.push(`      io: ["write:_scripts/*","write:_docs/*","write:_auditories/*"]`);
    lines.push(`      deny_write_root: true`);
    lines.push(`    metadata:`);
    lines.push(`      author: "${(e.author||'sóc-de-poble').replace(/"/g, '\\"')}"`);
    lines.push(`      last_updated: "${e.last_updated || new Date().toISOString().slice(0,10)}"`);
  }
  fs.writeFileSync(CATALOG_PATH, lines.join(os.EOL), 'utf8');
}

function determineDomain(meta, filename) {
  // Heuristics:
  // - if frontmatter has domain or tags containing core/domain/tactical use it
  // - else use filename keywords
  const name = filename.toLowerCase();
  if (meta) {
    if (meta.domain) return meta.domain;
    if (meta.tags) {
      const t = meta.tags.toLowerCase();
      if (t.includes('core')) return 'core';
      if (t.includes('tactical')) return 'tactical';
      if (t.includes('domain')) return 'domain';
    }
  }
  if (name.includes('a11y') || name.includes('access') || name.includes('core')) return 'core';
  if (name.includes('seo') || name.includes('marketing') || name.includes('content')) return 'domain';
  return 'tactical';
}

function checksumSha256(content) {
  const crypto = require('crypto');
  return 'sha256:' + crypto.createHash('sha256').update(content, 'utf8').digest('hex');
}

function main() {
  if (!fs.existsSync(SKILLS_ROOT)) {
    console.error('Error: _skills directory not found at', SKILLS_ROOT);
    process.exit(2);
  }

  // ensure domain folders exist
  for (const d of DOMAINS) safeMkdir(path.join(SKILLS_ROOT, d));

  const files = fs.readdirSync(SKILLS_ROOT).filter(f => f.endsWith('.md') && fs.statSync(path.join(SKILLS_ROOT, f)).isFile() && f !== 'catalog.yaml');
  if (files.length === 0) {
    console.log('No top-level .md skill files found in _skills/. Nothing to migrate.');
    process.exit(0);
  }

  const catalog = loadCatalog();

  for (const file of files) {
    const full = path.join(SKILLS_ROOT, file);
    const content = fs.readFileSync(full, 'utf8');
    const meta = readMdFrontmatter(content);
    const title = (meta && meta.title) || file.replace(/\.md$/i, '');
    const domain = determineDomain(meta, file);
    const domainDir = path.join(SKILLS_ROOT, domain);
    safeMkdir(domainDir);

    // create package folder
    const slug = slugify(title);
    const pkgDir = path.join(domainDir, slug);
    if (!fs.existsSync(pkgDir)) fs.mkdirSync(pkgDir, { recursive: true });

    // move original file into SKILL.md inside package
    const skillPath = path.join(pkgDir, 'SKILL.md');
    if (fs.existsSync(skillPath)) {
      // already migrated; skip moving but ensure catalog entry exists
      console.log(`Skipping ${file} (already migrated to ${skillPath})`);
    } else {
      fs.writeFileSync(skillPath, content, 'utf8');
      fs.unlinkSync(full);
      console.log(`Migrated ${file} -> ${path.relative(process.cwd(), skillPath)}`);
    }

    // create minimal package manifest (optional)
    const metaJsonPath = path.join(pkgDir, 'skill.json');
    const metaObj = {
      id: slug,
      version: (meta && meta.version) || '1.0.0',
      title: title,
      summary: (meta && meta.summary) || (content.split(/\r?\n/).slice(0,5).join(' ').slice(0,200)),
      entry: path.join(path.relative(SKILLS_ROOT, pkgDir), 'SKILL.md'),
      path: path.join(path.relative(SKILLS_ROOT, pkgDir), '/'),
      tags: (meta && meta.tags) ? meta.tags.split(',').map(s=>s.trim()) : [],
      author: (meta && meta.author) || 'sóc-de-poble',
      last_updated: new Date().toISOString().slice(0,10)
    };
    fs.writeFileSync(metaJsonPath, JSON.stringify(metaObj, null, 2), 'utf8');

    // add/update catalog manifest entry
    const stat = fs.statSync(skillPath);
    const checksum = checksumSha256(fs.readFileSync(skillPath, 'utf8'));
    const entry = {
      id: metaObj.id,
      version: metaObj.version,
      title: metaObj.title,
      summary: metaObj.summary,
      entry: metaObj.entry,
      path: metaObj.path,
      size_bytes: stat.size,
      checksum,
      tags: metaObj.tags,
      triggers: []
    };
    // avoid duplicates
    if (!catalog.manifest.find(m => m.id === entry.id)) catalog.manifest.push(entry);
  }

  // write catalog.yaml
  writeCatalog(catalog);
  console.log('Catalog updated at', CATALOG_PATH);
  console.log('Migration complete. Review created packages under _skills/<domain>/<slug>/');
}

main();
