const fs = require('fs');
let data = fs.readFileSync('src/shared/data.js', 'utf8');

const newCards = `
  { id: "pagina-termodinamica",
    town_id: 1,
    author: "Associació Sóc de Poble",
    author_avatar: "/assets/Mur/2026-04-01_1200_POST_s_c_de_poble_b_blia_de_disseny/logo-socdepoble-cuadrat-verd_60b5c7.svg",
    author_role: "admin",
    time: "Fa 2 hores",
    title: "Termodinàmica P2P",
    description: "La nostra filosofia de rendiment i eficiència.",
    comments: 24,
    image_url: ["/assets/Mur/2026-04-01_1200_POST_termodin_mica_p2p/nano_banana_vidre_1774195043000_b349f6.png"],
    type: "page",
    slug: "termodinamica",
    tags: ["#Hardware", "#Termodinamica", "#Poble"],
    lat: 38.5574,
    lng: -0.4692,
    created_at: new Date(Date.now() - 7200000).toISOString(),
    author_name: "L'Equip",
    town_name: "Poble Principal: Central",
  },
  // --- CONNECTIONS HUÉRFANAS ---
  { id: "pagina-ideoteca",
    town_id: 1,
    author: "L'Equip Sóc de Poble",
    author_avatar: "/assets/Mur/2026-04-01_1200_POST_s_c_de_poble_b_blia_de_disseny/logo-socdepoble-cuadrat-verd_60b5c7.svg",
    author_role: "admin",
    time: "Fa poc",
    title: "La Ideoteca",
    post_subtitle: "El nostre repositori d'idees",
    description: "Espai on guardem les nostres millors idees, referències i materials d'inspiració per al projecte.",
    type: "page",
    slug: "ideoteca",
    tags: ["#Ideoteca", "#Inspiració"],
    lat: 38.5574,
    lng: -0.4692,
    created_at: new Date(Date.now() - 300000).toISOString(),
    author_name: "L'Equip",
    town_name: "Poble Principal: Central",
  },
  { id: "pagina-aula-rural",
    town_id: 1,
    author: "L'Equip Sóc de Poble",
    author_avatar: "/assets/Mur/2026-04-01_1200_POST_s_c_de_poble_b_blia_de_disseny/logo-socdepoble-cuadrat-verd_60b5c7.svg",
    author_role: "admin",
    time: "Fa poc",
    title: "Aula Rural",
    post_subtitle: "Didàctica des del territori",
    description: "Aprenentatge, recursos didàctics i coneixement arrelat al nostre territori per a les futures generacions.",
    type: "page",
    slug: "aula-rural",
    tags: ["#AulaRural", "#Educació"],
    lat: 38.5574,
    lng: -0.4692,
    created_at: new Date(Date.now() - 400000).toISOString(),
    author_name: "L'Equip",
    town_name: "Poble Principal: Central",
  },
  { id: "pagina-dafo",
    town_id: 1,
    author: "L'Equip Sóc de Poble",
    author_avatar: "/assets/Mur/2026-04-01_1200_POST_s_c_de_poble_b_blia_de_disseny/logo-socdepoble-cuadrat-verd_60b5c7.svg",
    author_role: "admin",
    time: "Fa poc",
    title: "Anàlisi DAFO",
    post_subtitle: "Debilitats, Amenaces, Fortaleses, Oportunitats",
    description: "L'anàlisi estratègic complet de Sóc de Poble per entendre on estem i cap a on anem.",
    type: "page",
    slug: "dafo",
    tags: ["#DAFO", "#Estratègia"],
    lat: 38.5574,
    lng: -0.4692,
    created_at: new Date(Date.now() - 500000).toISOString(),
    author_name: "L'Equip",
    town_name: "Poble Principal: Central",
  },
  { id: "pagina-canon",
    town_id: 1,
    author: "L'Equip Sóc de Poble",
    author_avatar: "/assets/Mur/2026-04-01_1200_POST_s_c_de_poble_b_blia_de_disseny/logo-socdepoble-cuadrat-verd_60b5c7.svg",
    author_role: "admin",
    time: "Fa poc",
    title: "Cànon de Disseny",
    post_subtitle: "Estètica i Filosofia Trellat",
    description: "Les regles de ferro del disseny, proporcions geomètriques i la filosofia visual darrere de Sóc de Poble.",
    type: "page",
    slug: "canon",
    tags: ["#Canon", "#Disseny", "#Trellat"],
    lat: 38.5574,
    lng: -0.4692,
    created_at: new Date(Date.now() - 600000).toISOString(),
    author_name: "L'Equip",
    town_name: "Poble Principal: Central",
  },
  { id: "pagina-didactica",
    town_id: 1,
    author: "L'Equip Sóc de Poble",
    author_avatar: "/assets/Mur/2026-04-01_1200_POST_s_c_de_poble_b_blia_de_disseny/logo-socdepoble-cuadrat-verd_60b5c7.svg",
    author_role: "admin",
    time: "Fa poc",
    title: "Didàctica",
    post_subtitle: "Material educatiu",
    description: "Recursos didàctics adaptats per a escoles, instituts i activitats de formació.",
    type: "page",
    slug: "didactica",
    tags: ["#Didàctica", "#Escola"],
    lat: 38.5574,
    lng: -0.4692,
    created_at: new Date(Date.now() - 700000).toISOString(),
    author_name: "L'Equip",
    town_name: "Poble Principal: Central",
  },
  { id: "pagina-fantasmes",
    town_id: 1,
    author: "L'Equip Sóc de Poble",
    author_avatar: "/assets/Mur/2026-04-01_1200_POST_s_c_de_poble_b_blia_de_disseny/logo-socdepoble-cuadrat-verd_60b5c7.svg",
    author_role: "admin",
    time: "Fa poc",
    title: "Memorial de Fantasmes",
    post_subtitle: "Recordant allò que ja no hi és",
    description: "Un espai de memòria per a llocs, costums i oficis que han desaparegut del nostre entorn.",
    type: "page",
    slug: "fantasmes",
    tags: ["#Memòria", "#Fantasmes"],
    lat: 38.5574,
    lng: -0.4692,
    created_at: new Date(Date.now() - 800000).toISOString(),
    author_name: "L'Equip",
    town_name: "Poble Principal: Central",
  },
  { id: "pagina-playground",
    town_id: 1,
    author: "L'Equip Sóc de Poble",
    author_avatar: "/assets/Mur/2026-04-01_1200_POST_s_c_de_poble_b_blia_de_disseny/logo-socdepoble-cuadrat-verd_60b5c7.svg",
    author_role: "admin",
    time: "Fa poc",
    title: "Playground",
    post_subtitle: "Zona de proves",
    description: "L'espai d'experimentació on provem noves idees, components i conceptes arquitectònics abans de fer-los oficials.",
    type: "page",
    slug: "playground",
    tags: ["#Proves", "#Playground", "#Codi"],
    lat: 38.5574,
    lng: -0.4692,
    created_at: new Date(Date.now() - 900000).toISOString(),
    author_name: "L'Equip",
    town_name: "Poble Principal: Central",
  },
  { id: "pagina-cronica",
    town_id: 1,
    author: "L'Equip Sóc de Poble",
    author_avatar: "/assets/Mur/2026-04-01_1200_POST_s_c_de_poble_b_blia_de_disseny/logo-socdepoble-cuadrat-verd_60b5c7.svg",
    author_role: "admin",
    time: "Fa poc",
    title: "Crònica de Sessions",
    post_subtitle: "El diari de bord",
    description: "El registre de les nostres sessions de treball, acords i decisions de disseny.",
    type: "page",
    slug: "cronica",
    tags: ["#Crònica", "#Diari"],
    lat: 38.5574,
    lng: -0.4692,
    created_at: new Date(Date.now() - 1000000).toISOString(),
    author_name: "L'Equip",
    town_name: "Poble Principal: Central",
  },
`;

const anchor = '  { id: "post-nano-banana-vidre-1",';
data = data.replace(anchor, newCards + '\n' + anchor);

fs.writeFileSync('src/shared/data.js', data);
console.log('Fixed data.js successfully with the new cards!');
