// Dades de mercat recuperades de la versió original.
export const MOCK_MARKET_ITEMS = [{
  id: 'samarreta-soc-de-poble',
  type: 'product',
  title: 'Samarreta Sóc de Poble',
  description: "L'edició definitiva amb el Logotip Complet (Mapa del Tresor). Cotó Roly de màxima qualitat. #MapaDelTresor #SócDePoble",
  price: '15.00€',
  seller: 'Sóc de Poble',
  avatar_url: '/assets/system/ui/logo-socdepoble-cuadrat-verd.svg',
  author_name: 'Sóc de Poble',
  author_role: 'business',
  author_id: 'soc-de-poble_official',
  author_entity_id: 'socdepoble',
  official: true,
  pinned: true,
  variations: [{
    name: 'Edició Gris Plom',
    price: '15.00€',
    description: 'Cotó Roly Gris. Discreta i elegant.',
    image: '02-samarreta-socdepoble-roly-plom-oscur-1024px.png'
  }, {
    name: 'Edició Verda',
    price: '15.00€',
    description: 'Edició especial en color verd pi.',
    image: 'samarreta-socdepoble-verd-638px.jpg',
    stock_status: 'Esgotat'
  }],
  images: ['01-chica-jersey.png', '02-samarreta-socdepoble-roly-plom-oscur-1024px.png', '03-young-man-tshirt.png', '04-iaia-tshirt.png', '06-group-tshirt.png', '07-rustic-detail.png', '08-javi-llinares-perfil-1024px.jpg'],
  category_slug: 'roba',
  tag: 'Merchandising',
  is_pinned: true,
  pinned_position: 1,
  lat: 38.5582,
  lng: -0.4413,
  created_at: '2026-03-22T22:33:00.000Z'
}, {
  id: 'mel-de-muntanya-la-torre',
  slug: 'mel-de-muntanya-la-torre',
  type: 'product',
  title: 'Mel de Muntanya (La Torre)',
  description: 'Mel artesanal collida a les vores de serra. Potent, clara i amb gust de flor de romer.',
  price: '8.50€',
  seller: 'Rosa (Mel de la Torre)',
  avatar_url: '/assets/uploads/companies/mercat/flowers_bouquet.png',
  author_name: 'Rosa',
  author_role: 'business',
  author_id: 'mock-business-mel-torre',
  author_entity_id: 'mock-business-mel-torre',
  category_slug: 'alimentacio',
  tag: 'Producte local',
  is_pinned: true,
  pinned_position: 2,
  image_url: '/assets/uploads/companies/mercat/flowers_bouquet.png',
  lat: 38.5919,
  lng: -0.4184,
  created_at: '2026-03-22T21:10:00.000Z'
}, {
  id: 'oli-d-oliva-verge',
  slug: 'oli-d-oliva-verge',
  type: 'product',
  title: "Oli d'Oliva Verge Extra",
  description: 'Oli de primera premsada, elegant i viu. Ideal per a torrades, ensalades i cuina de casa.',
  price: '9.00€',
  seller: 'El Cronista',
  avatar_url: '/assets/uploads/companies/mercat/aitana.png',
  author_name: 'El Cronista',
  author_role: 'business',
  author_id: 'mock-business-oli',
  author_entity_id: 'mock-business-oli',
  category_slug: 'alimentacio',
  tag: 'Gourmet',
  image_url: '/assets/uploads/companies/mercat/aitana.png',
  lat: 38.6083,
  lng: -0.2721,
  created_at: '2026-03-22T20:55:00.000Z'
}, {
  id: 'cistella-de-l-hort',
  slug: 'cistella-de-l-hort',
  type: 'product',
  title: "Cistella de l'Hort",
  description: 'Cistella setmanal amb verdura de temporada i tomaca de ramellet, directa del camp.',
  price: '24.00€',
  seller: 'Cooperativa de la Vall',
  avatar_url: '/assets/uploads/companies/mercat/generic_market.png',
  author_name: 'Cooperativa de la Vall',
  author_role: 'business',
  author_id: 'mock-business-hort',
  author_entity_id: 'mock-business-hort',
  category_slug: 'horta',
  tag: 'Km0',
  image_url: '/assets/uploads/companies/mercat/generic_market.png',
  lat: 38.563,
  lng: -0.2618,
  created_at: '2026-03-22T19:40:00.000Z'
}, {
  id: 'bossa-de-tela-del-mas',
  slug: 'bossa-de-tela-del-mas',
  type: 'product',
  title: 'Bossa de Tela del Mas',
  description: "Reusable, robusta i amb l'estètica del portal. Per anar al mercat sense gastar plàstic.",
  price: '6.00€',
  seller: 'Sóc de Poble',
  avatar_url: '/assets/system/ui/logo-socdepoble-cuadrat-verd.svg',
  author_name: 'Sóc de Poble',
  author_role: 'business',
  author_id: 'soc-de-poble_official',
  author_entity_id: 'socdepoble',
  official: true,
  is_pinned: true,
  pinned_position: 3,
  category_slug: 'roba',
  tag: 'Merchandising',
  image_url: '/assets/uploads/companies/mercat/camiseta_portada.png',
  lat: 38.5582,
  lng: -0.4413,
  created_at: '2026-03-22T18:05:00.000Z'
}];
